<?php

namespace App\Helpers;

class ConahcytProgramas
{
    public static function all(): array
    {
        return [
            'FONDO_INSTITUCIONAL',
            'FONDO_MIXTO',
            'FONDO_MIXTO_AS',
            'FONDO_MIXTO_BC',
            'FONDO_MIXTO_BCS',
            'FONDO_MIXTO_CC',
            'FONDO_MIXTO_CS',
            'FONDO_MIXTO_CH',
            'FONDO_MIXTO_DF',
            'FONDO_MIXTO_CIUDAD_JUAREZ',
            'FONDO_MIXTO_CL',
            'FONDO_MIXTO_CM',
            'FONDO_MIXTO_DG',
            'FONDO_MIXTO_ESTADO_MEXICO',
            'FONDO_MIXTO_GT',
            'FONDO_MIXTO_GR',
            'FONDO_MIXTO_HG',
            'Fondo Mixto Jalisco',
            'Fondo Mixto Michoacán',
            'Fondo Mixto Morelos',
            'Fondo Mixto Municipio de La Paz',
            'Fondo Mixto Municipio de Puebla',
            'Fondo Mixto Nayarit',
            'Fondo Mixto Nuevo León',
            'Fondo Mixto Oaxaca',
            'Fondo Mixto Puebla',
            'Fondo Mixto Querétaro',
            'Fondo Mixto Quintana Roo',
            'Fondo Mixto San Luis Potosí',
            'Fondo Mixto Sinaloa',
            'Fondo Mixto Sonora',
            'Fondo Mixto Tabasco',
            'Fondo Mixto Tamaulipas',
            'Fondo Mixto Tlaxcala',
            'Fondo Mixto Veracruz',
            'Fondo Mixto Yucatán',
            'Fondo Mixto Zacatecas',
            'Fondo sectorial',
            'Fondo Sectorial CONACYT Secretaría de Energía Hidrocarburos',
            'Fondo Sectorial CONACYT Secretaría de Energía Sustentabilidad Energética',
            'Fondo Sectorial CONACYT SEGOB CNS para la Seguridad Pública',
            'Fondo Sectorial Convocatoria de Investigación Científica Básica',
            'Fondo Sectorial Convocatoria de Investigación en Juventud',
            'Fondo Sectorial Convocatoria de Investigación para la Educación Indígena e Intercultural',
            'Fondo Sectorial Convocatoria de la Administración Federal de Servicios Educativos en el Distrito Federal (AFSEDF)',
            'Fondo Sectorial Convocatoria de la Subsecretaría de Educación Básica',
            'Fondo Sectorial de Innovación (FINNOVA)',
            'Fondo Sectorial de Investigación Ambiental',
            'Fondo Sectorial de Investigación CONACYT INEGI',
            'Fondo Sectorial de Investigación, Desarrollo Tecnológico e Innovación del Ejército y Fuerza Aérea Mexicanos',
            'Fondo Sectorial de Investigación, Desarrollo Tecnológico e Innovación en Actividades Espaciales CONACYT AEM',
            'Fondo Sectorial de Investigación en Materias Agrícola, Pecuaria, Acuacultura, Agrobiotecnología y Recursos Fitogenéticos',
            'Fondo Sectorial de Investigación en Salud y Seguridad Social',
            'Fondo Sectorial de Investigación INIFED CONACYT',
            'Fondo Sectorial de Investigación para el Desarrollo Aeroportuario y la Navegación Aérea',
            'Fondo Sectorial de Investigación para el Desarrollo Social',
            'Fondo Sectorial de Investigación para la Educación',
            'Fondo Sectorial de Investigación para la Evaluación de la Educación CONACYT INEE',
            'Fondo Sectorial de Investigación SECTUR CONACYT',
            'Fondo Sectorial de Investigación SRE CONACYT',
            'Fondo Sectorial de Investigación y Desarrollo en Ciencias Navales',
            'Fondo Sectorial de Investigación y Desarrollo INMUJERES CONACYT',
            'Fondo Sectorial de Investigación y Desarrollo sobre el Agua',
            'Fondo Sectorial Fondo de Desarrollo Científico y Tecnológico para el Fomento de la Producción y Financiamiento de Vivienda y el Crecimiento del Sector Habitacional',
            'Fondo Sectorial Fondo de Innovación Tecnológica (FIT)',
            'Fondo Sectorial Investigaciones Acerca de la Violencia de Género. Investigaciones con Enfoque de Género',
            'Fondo Sectorial para Investigación y Desarrollo Tecnológico en Energía',
            'Fondo Sectorial para la Investigación, el Desarrollo y la Innovación Tecnológica Forestal',
            'Fondo Sectorial Subcuenta de Investigación para la Evaluación de la Educación',
            'Fondos y Apoyos Institucionales - Apoyos Complementarios para la Adquisición de Equipo Científico',
            'Fondos y Apoyos Institucionales - Estímulos Fiscales a la Investigación y Desarrollo de Tecnología (EFIDT)',
            'Fondos y Apoyos Institucionales - Fondo de Cooperación Internacional en Ciencia y Tecnología del CONACYT (FONCICY)',
            'Fondos y Apoyos Institucionales -Fondo Institucional de Fomento Regional para el Desarrollo Científico, Tecnológico y de Innovación (FORDECYT)',
            'Fondos y Apoyos Institucionales - Fondo Institucional del CONACYT (FOINS)',
            'Fondos y Apoyos Institucionales - Fondo para el Fomento y Apoyo a la Investigación Científica y Tecnológica en Bioseguridad y Biotecnología (Fondo CIBIOGEM)',
            'Fondos y Apoyos Institucionales - Programa de Apoyos para Actividades Científicas Tecnológicas y de Innovación',
            'Fondos y Apoyos Institucionales Programa Estímulos a la Innovación (PEI)',
            'Programa CONACYT- Apoyo a Madres Jefas de Familia',
            'Programa CONACYT - Beca al Extranjero',
            'Programa CONACYT - Beca Mixta',
            'Programa CONACYT - Beca Nacional',
            'Programa CONACYT - Estancias Posdoctorales',
            'Programa CONACYT - Estancias Sabáticas',
            'Programa CONACYT - Formación de Alto Nivel para la Administración Pública',
            'Programa CONACYT -Fortalecimiento Académico para Indígenas',
            'Programa CONACYT - Jóvenes Talentos',
            'Programa CONACYT - Otro',
            'Programa CONACYT - Repatriaciones y Retenciones',
        ];
    }
}
